[pytest]
pythonpath = .
asyncio_mode = auto
addopts = -p no:warnings --cov=app --cov-report=html --cov-report=term-missing
log_cli = true
log_cli_level = INFO
log_format = %(asctime)s - %(levelname)s - %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
markers =
    asyncio: mark a test as async